### ISSUE TITLE
what's  the different between  prestodb  with  prestosql?

### ISSUE THREAD

**Issue by newluhuibiao** [prestosql/presto#1434] opened 2019-09-03 11:32 UTC
prestodb project website is https://prestodb.github.io/

**Comment by kokosing** [comment] 2019-09-03 11:41
Duplicate of https://github.com/prestosql/presto/issues/380

**Closed by kokosing** 2019-09-03 11:41 UTC

**Comment by kokosing** [comment] 2019-09-03 13:21
@newluhuibiao please see #380. It gives high overview of the differences.
If you have further questions, please join Presto Slack (https://prestosql.io/community.html) where you can learn more. See you there!
