### ISSUE TITLE
Presto GUI prompts for Client certificate after enabling HTTPS

### ISSUE THREAD

**Issue by DRavikanth** [prestosql/presto#4644] opened 2020-07-30 21:03 UTC
After enabling HTTPS for Presto on trying to access the GUI on HTTPS link the browser prompts for a client certificate. Can this be addressed ?

Thanks,
Ravi

**Comment by tooptoop4** [comment] 2020-07-31 08:29
duplicate of https://github.com/prestosql/presto/issues/3649

**Comment by findepi** [comment] 2020-07-31 09:18
@tooptoop4 thanks, my fault

@DRavikanth thanks for reporting the issue, let's continue under https://github.com/prestosql/presto/issues/3649

**Closed by findepi** 2020-07-31 09:18 UTC
Labels: ui
