### ISSUE TITLE
Support kerberos authentication for Kudu connector.

### ISSUE THREAD

**Issue by sumit-gupta-sgt** [prestosql/presto#5367] opened 2020-10-01 00:11 UTC
My Kudu Cluster is Kerberos enabled, Do we have support for enable Kerberos in kudu catalog file?

**Comment by ebyhr** [comment] 2020-10-01 02:41
Going to close as duplicate of #1237. There is an ongoing PR #3549.

**Closed by ebyhr** 2020-10-01 02:41 UTC
