### ISSUE TITLE
Could not create connection to mysql database server

### ISSUE THREAD

**Issue by Svti** [prestosql/presto#3663] opened 2020-05-07 13:05 UTC
io.prestosql.spi.PrestoException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getTableNames(BaseJdbcClient.java:211)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getTableNames$2(StatisticsAwareJdbcClient.java:85)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableNames(StatisticsAwareJdbcClient.java:85)
	at io.prestosql.plugin.jdbc.ForwardingJdbcClient.getTableNames(ForwardingJdbcClient.java:70)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.lambda$new$0(CachingJdbcClient.java:74)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:434)
	at io.prestosql.plugin.jdbc.CachingJdbcClient.getTableNames(CachingJdbcClient.java:97)
	at io.prestosql.plugin.jdbc.JdbcMetadata.listTables(JdbcMetadata.java:208)
	at io.prestosql.metadata.MetadataManager.listTables(MetadataManager.java:540)
	at io.prestosql.metadata.MetadataListing.listTables(MetadataListing.java:65)
	at io.prestosql.connector.system.jdbc.TableJdbcTable.cursor(TableJdbcTable.java:101)
	at io.prestosql.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:131)
	at io.prestosql.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
	at io.prestosql.spi.connector.RecordPageSource.<init>(RecordPageSource.java:39)
	at io.prestosql.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:110)
	at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:254)
	at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:182)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:306)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
	at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
	at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:149)
	at io.prestosql.operator.Driver.processInternal(Driver.java:379)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_332____20200426_025556_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.GeneratedConstructorAccessor19353.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2095)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2020)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor336.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at io.prestosql.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:63)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.lambda$openConnection$0(StatisticsAwareConnectionFactory.java:42)
	at io.prestosql.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:35)
	at io.prestosql.plugin.jdbc.jmx.StatisticsAwareConnectionFactory.openConnection(StatisticsAwareConnectionFactory.java:42)
	at io.prestosql.plugin.jdbc.BaseJdbcClient.getTableNames(BaseJdbcClient.java:198)

**Comment by tooptoop4** [comment] 2020-05-07 17:10
@Svti can you share your catalog properties file?

**Comment by Svti** [comment] 2020-05-08 10:11
I'm sure this can be connected ,  But it's happend sometimes

**Comment by HuaiNianZhanZhengNianDai** [comment] 2020-07-08 04:22
yes i have met

**Comment by Leeviiii** [comment] 2020-09-28 07:29
i have met ..there is any method to solve this question?

**Comment by Leeviiii** [comment] 2020-09-28 07:33
this is a '=' in my password? do it matter?

**Comment by findepi** [comment] 2020-09-28 07:39
@Leeviiii 

> this is a '=' in my password? do it matter?

although in properties file you can escape it as `\=`, it shouldn't matter if you do not.
Does it contain also backslash `\` or any whitespace?

**Comment by findepi** [comment] 2020-09-28 07:40
BTW I will close this as not-an-issue in Presto, unless someone can provide some repro steps.
(the issue is not actionable in its current form)

We can continue conversation here, or on `#troubleshooting` channel on [our slack](https://prestosql.io/slack.html).
See you there!

**Closed by findepi** 2020-09-28 07:40 UTC

**Comment by Leeviiii** [comment] 2020-09-28 07:47
connector.name=mysql
connection-url=jdbc:mysql://ip:port
connection-user=user
connection-password=passwdxx=
this is my conf

**Comment by mjh568412187** [comment] 2022-12-07 08:44
I encountered the same error, the version of trino is 403 Trino link mysql8 is ok, trino link mysql5.7 the error is as follows

trino:dwd> SHOW SCHEMAS from mysql_cdpdev01;

Query 20221207_083249_00003_ur92f, FAILED, 2 nodes
Splits: 11 total, 0 done (0.00%)
4.18 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20221207_083249_00003_ur92f failed: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
