### ISSUE TITLE
Presto UDF 

### ISSUE THREAD

**Issue by wajahatahmed245** [prestosql/presto#1187] opened 2019-07-25 14:21 UTC
I have made a jar file and I am placing that jar file as follow but I am still not able to use the functions in presto CLI 
![image_720](https://user-images.githubusercontent.com/32391965/61882188-61b3f800-af11-11e9-9bee-1814780b38d0.png)
![image](https://user-images.githubusercontent.com/32391965/61882220-72646e00-af11-11e9-92ad-430cc990175c.png)

**Comment by electrum** [comment] 2019-07-26 00:55
I think the problem is that the directory needs to be directly under the `plugin` directory. You have it in a nested subdirectory. So it should work if you rename it to `plugin/udfs-scalar`.

Another issue is that you using version `0.222` of Presto. It will be easier to help you if you update to the latest version, `316`: https://prestosql.io/download.html

When the server starts, it will print information about the plugins that are loaded. You should see something like this:
```
io.prestosql.server.PluginManager	-- Loading plugin /usr/lib/presto/plugin/ml --
io.prestosql.server.PluginManager	Installing io.prestosql.plugin.ml.MLPlugin
io.prestosql.server.PluginManager	Registering functions from io.prestosql.plugin.ml.MLFunctions
io.prestosql.server.PluginManager	-- Finished loading plugin /usr/lib/presto/plugin/ml --
```

**Comment by findepi** [comment] 2019-09-24 21:00
@wajahatahmed245 i assume you resolved the problem, therefore closing the issue.
If this is not the case, let's continue on the `#troubleshooting` slack channel.

**Closed by findepi** 2019-09-24 21:00 UTC
