### ISSUE TITLE
Flaky io.prestosql.jdbc.TestPrestoDriver#testQueryCancelByInterrupt

### ISSUE THREAD

**Issue by wendigo** [prestosql/presto#2539] opened 2020-01-17 14:13 UTC
```  
java.lang.AssertionError: expected [FAILED] but found [RUNNING]
 	at org.testng.Assert.fail(Assert.java:94)
 	at org.testng.Assert.failNotEquals(Assert.java:513)
 	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
 	at org.testng.Assert.assertEquals(Assert.java:179)
 	at io.prestosql.jdbc.TestPrestoDriver.testQueryCancelByInterrupt(TestPrestoDriver.java:786)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 	at java.lang.Thread.run(Thread.java:748)
```

https://github.com/prestosql/presto/pull/2527/checks?check_run_id=395077575

**Comment by martint** [comment] 2020-01-17 15:25
Duplicate of https://github.com/prestosql/presto/issues/2497

**Closed by martint** 2020-01-17 15:25 UTC
Labels: bug, test
