### ISSUE TITLE
Internal Communication getting checked for authentication even when HTTPS is not enabled

### ISSUE THREAD

**Issue by imjalpreet** [prestosql/presto#3594] opened 2020-04-30 23:23 UTC
### Observation
Presto Release: **332** 
I have not enabled Secure Internal Communication, i.e. **internal-communication.https.required** has it's default value **false**.  I have observed that all the internal communication requests are still trying to get authenticated and sometimes even log: 

```
2020-04-19T10:14:28.114Z        ERROR   http-worker-1699        io.prestosql.server.InternalAuthenticationManager       Internal authentication failed
io.jsonwebtoken.ExpiredJwtException: JWT expired at 2020-04-19T10:14:21Z. Current time: 2020-04-19T10:14:28Z, a difference of 7114 milliseconds.  Allowed clock skew: 0 milliseconds.
```
Once this is logged in the coordinator's server logs, the respective worker cannot communicate with the coordinator or any other worker. 

#### Why this is happening?
Since there is no check for whether secure communication has been enabled(and since the change to enable Internal JWT by default), the header _**X-Presto-Internal-Bearer**_ is getting added to all requests. Due to this even when **HTTPS** is not enabled, every request(when it reaches **AuthenticationFilter**) is treated as if HTTPS is enabled and JWT is tried to parse which when throws the above-mentioned error results in loss of communication between the concerned worker and the rest of the cluster. (Also, default value of shared secret is being set to Environment). 

Let me know in case any additional details are required. I have implemented a fix for the same and tested on my cluster.

**Comment by electrum** [comment] 2020-04-30 23:38
Internal requests are always authenticated, by design, even over HTTP. This is less effective if an attacker can sniff network traffic, but is better than nothing and is effective in other scenarios.

The generated JWT are valid for five minutes, so I am guessing that that the machines in your cluster have significant clock skew. Please verify that the clocks are reasonably synchronized.

**Comment by tooptoop4** [comment] 2020-05-06 15:06
@imjalpreet pls share the fix

**Comment by tooptoop4** [comment] 2020-05-09 10:39
is it just a case of reverting https://github.com/prestosql/presto/commit/c32c44b7c070f784d90fad6ec7c881b4eaa158da ?
https://github.com/prestosql/presto/issues/3518 seems related too

**Comment by imjalpreet** [comment] 2020-05-13 22:46
@tooptoop4 as @electrum suggested that internal requests are always authenticated and this could have happened due to clock skew between the worker nodes and the coordinator, we won't have to fix this. In case you are also facing the same issue, maybe you can also verify whether the nodes are synchronized.

**Comment by findepi** [comment] 2020-05-14 11:29
> I am guessing that that the machines in your cluster have significant clock skew

https://github.com/prestosql/presto/issues/3730

**Comment by dain** [comment] 2020-07-19 01:11
It looks like this question is resolved, so I'm going to close this issue for now.  If you have more questions. please reopen.

**Closed by dain** 2020-07-19 01:11 UTC
Labels: bug
