### ISSUE TITLE
MongoDB case sensitive support

### ISSUE THREAD

**Issue by d4rth-v4d3r** [prestosql/presto#3593] opened 2020-04-30 22:03 UTC
I have a MongoDb database with collections that have camelCase naming convention, but I'm unable to query tables like: "userTags" or "customerTypes". Is there any way to make PrestoDb Mongo connector to work with this use case?

**Comment by ebyhr** [comment] 2020-04-30 22:32
Going to close because this is a duplicate of https://github.com/prestosql/presto/issues/1102. 
It's not yet supported.

**Closed by ebyhr** 2020-04-30 22:32 UTC

**Comment by d4rth-v4d3r** [comment] 2020-04-30 22:58
Is there any plans to support it? @ebyhr

**Comment by ebyhr** [comment] 2020-04-30 23:41
@d4rth-v4d3r Please take a look at the above issue. It has linked PR.

**Comment by d4rth-v4d3r** [comment] 2020-05-01 03:43
Thanks @ebyhr I will check
