### ISSUE TITLE
SHOW CATALOGS fails with "Internal error" when all catalogs filtered out by access control

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#2593] opened 2020-01-23 10:33 UTC
There always is a catalog. If nothing is installed, there is a `system` catalog.
However, `AccessControl` may legitimately filter it out.

Then --
```
presto:default> SHOW CATALOGS;
Query 20200123_103158_00002_4u426 failed: Internal error
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitValues(StatementAnalyzer.java:1477)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitValues(StatementAnalyzer.java:287)
	at io.prestosql.sql.tree.Values.accept(Values.java:55)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:302)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:1082)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:287)
	at io.prestosql.sql.tree.AliasedRelation.accept(AliasedRelation.java:71)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:302)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2204)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1161)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:287)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:302)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:312)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:853)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:287)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:302)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:279)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:219)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:178)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:95)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:712)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:119)
	at io.prestosql.$gen.Presto_null__testversion____20200123_102923_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martint** [comment] 2020-01-24 18:00
The issue is that the rewrite is creating a VALUES syntax node with no rows. 

The long-term fix for this is to add first-class support for `SHOW xxx` to the planner instead of relying on syntactic rewrites and create an empty ValuesNode directly. In the short term, we'll have to fix it by synthesizing a `VALUES` with at least one bogus row and a `WHERE false` on top of it.

**Closed** 2020-02-07 17:51 UTC
Labels: bug, good first issue
