### ISSUE TITLE
support dynamic connector configuration

### ISSUE THREAD

**Issue by allendang001** [prestosql/presto#5534] opened 2020-10-13 08:11 UTC
Prestosql does not support adding a new catalog when presto cluster is running, this leads to no way to support the join operation of an existing catalog and a new catalog without restarting. 
Is there any solution at present?

**Comment by ebyhr** [comment] 2020-10-13 08:27
Going to close as duplicate of #2110. It's not possible now.

**Closed by ebyhr** 2020-10-13 08:27 UTC

**Comment by allendang001** [comment] 2020-10-13 08:42
what is the reason?

**Comment by allendang001** [comment] 2020-10-13 08:42
> Going to close as duplicate of #2110. It's not possible now.

what is the reason?

**Comment by findepi** [comment] 2020-10-13 08:48
Let's keep the discussion under #2110 issue.
if you have more questions you can also reach out on #dev on [our slack](https://prestosql.io/slack.html).
