### ISSUE TITLE
REST as SOURCE

### ISSUE THREAD

**Issue by yapnel** [prestosql/presto#5227] opened 2020-09-19 10:01 UTC
Can Presto consume REST endpoints as data source?

**Comment by tooptoop4** [comment] 2020-09-19 14:37
duplicate of https://github.com/prestosql/presto/issues/704

**Comment by findepi** [comment] 2020-09-19 14:41
closing in favor of https://github.com/prestosql/presto/issues/704

see also https://prestosql.io/docs/current/develop/example-http.html

**Closed by findepi** 2020-09-19 14:41 UTC
