### ISSUE TITLE
Flaky io.prestosql.plugin.memory.TestMemorySmoke.testCrossJoinDynamicFiltering

### ISSUE THREAD

**Issue by wendigo** [prestosql/presto#6266] opened 2020-12-09 11:50 UTC
```
2020-12-09T11:01:32.4953892Z [ERROR] testCrossJoinDynamicFiltering(io.prestosql.plugin.memory.TestMemorySmoke)  Time elapsed: 6.013 s  <<< FAILURE!
2020-12-09T11:01:32.4962845Z java.lang.AssertionError:  expected [[I@6d1255ec] but found [[Ljava.lang.Object;@2b444108]
2020-12-09T11:01:32.4969929Z 	at org.testng.Assert.fail(Assert.java:94)
2020-12-09T11:01:32.4974968Z 	at org.testng.Assert.failNotEquals(Assert.java:513)
2020-12-09T11:01:32.4990711Z 	at org.testng.Assert.assertArrayEquals(Assert.java:158)
2020-12-09T11:01:32.4994434Z 	at org.testng.Assert.assertEquals(Assert.java:113)
2020-12-09T11:01:32.4998424Z 	at org.testng.Assert.assertEquals(Assert.java:179)
2020-12-09T11:01:32.5006057Z 	at io.prestosql.plugin.memory.TestMemorySmoke.assertDynamicFiltering(TestMemorySmoke.java:325)
2020-12-09T11:01:32.5012645Z 	at io.prestosql.plugin.memory.TestMemorySmoke.testCrossJoinDynamicFiltering(TestMemorySmoke.java:294)
2020-12-09T11:01:32.5031743Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-09T11:01:32.5044453Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-09T11:01:32.5070306Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-09T11:01:32.5076948Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-09T11:01:32.5085028Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-12-09T11:01:32.5090937Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-12-09T11:01:32.5097044Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-12-09T11:01:32.5103482Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-12-09T11:01:32.5111027Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-12-09T11:01:32.5117743Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-12-09T11:01:32.5126259Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-09T11:01:32.5134407Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-09T11:01:32.5139152Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by wendigo** [comment] 2020-12-09 11:50
https://github.com/prestosql/presto/pull/6241/checks?check_run_id=1523270610

**Comment by wendigo** [comment] 2020-12-09 11:50
cc @sopel39

**Comment by sopel39** [comment] 2020-12-09 11:59
This suggests: https://github.com/prestosql/presto/issues/5172

**Comment by findepi** [comment] 2020-12-09 22:43
can the method (and similar ones, in TestKuduIntegrationDynamicFilter) get annotated as Flaky due to #5172 ?

**Comment by findepi** [comment] 2020-12-15 12:37
> can the method (and similar ones, in TestKuduIntegrationDynamicFilter) get annotated as Flaky due to #5172 ?

posted https://github.com/prestosql/presto/pull/6346 and then the issue should be closed as a duplicate of https://github.com/prestosql/presto/issues/5172

**Comment by findepi** [comment] 2020-12-15 22:03
Closing in favor of https://github.com/prestosql/presto/issues/5172

**Closed by findepi** 2020-12-15 22:03 UTC
Labels: bug, test
