### ISSUE TITLE
Unable to query Mongodb nested document using presto

### ISSUE THREAD

**Issue by skarsri** [prestosql/presto#734] opened 2019-05-09 19:42 UTC
Currently we are using Presto ver 0.309. From Presto cli, we are unable to query document based on shipping address zip.

Does Presto-MongoDB connector support multi-level nested document?

sample contact collection
{
   _id:ObjectId(""),
"name":"",
"addresses":{
"shipping":{
"street":"",
"zip":""
},
"billing":{
"street":"",
"zip":""
}
}
}

**Comment by ebyhr** [comment] 2019-05-11 10:40
Could you please share the error message? I could receive a result using the definition.
```
presto:test> select * from mongodb.test.test;
 name |                        addresses                        
------+---------------------------------------------------------
 a    | {shipping={street=b, zip=c}, billing={street=d, zip=e}} 
```

**Comment by abz53378** [comment] 2019-05-27 11:13
I guess it's caused by the wrong `_schema` in your MongoDB, as the [docs#Table Definition](https://prestodb.github.io/docs/current/connector/mongodb.html) mentioned, MongoDB connector automatically guesses the schema of your data and write back in your MongoDB. You can check whether it's correct by `db.getCollection("_schema").find()`

And the [source code here](https://github.com/prestosql/presto/blob/master/presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java#L468) explains why it may miss some fields, it always takes the **first** collection to guess the filed type

**Comment by ebyhr** [comment] 2020-04-06 01:32
Going to close this issue because nested field is already supported. Please reopen if @abz53378's suggestion doesn't work.

**Closed by ebyhr** 2020-04-06 01:32 UTC
