### ISSUE TITLE
Python Client for Kerberized Presto

### ISSUE THREAD

**Issue by VicoWu** [prestosql/presto#656] opened 2019-04-22 06:50 UTC
I am currently working on and testing python presto client for kerberized presto server. 
The presto python client I am using is [presto-python-client](https://github.com/prestodb/presto-python-client)

But whaterver I do, the client reports `CERTIFICATE_VERIFY_FAILED`: 
```
Traceback (most recent call last):
  File "/Users/chang.wu/work/workspace/hulu-github-src/hadoop-security/code-layer-verification/src/main/java/com/hulu/security/presto/PrestoPythonClient.py", line 42, in <module>
    cur.execute('SHOW tables')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prestodb/dbapi.py", line 228, in execute
    result = self._query.execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prestodb/client.py", line 520, in execute
    response = self._request.post(self._sql)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prestodb/client.py", line 347, in post
    proxies=PROXIES,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='iadhadoop-b34.server.hulu.com', port=7778): Max retries exceeded with url: /v1/statement (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
```
From the server, I add debug log for SSL and the server reports unknown ca error: 
```
9-04-21T21:47:51.154-0700	INFO	http-worker-197	stdout	Supported Signature Algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA256withDSA, SHA224withECDSA, SHA224withRSA, SHA224withDSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA
2019-04-21T21:47:51.154-0700	INFO	http-worker-197	stdout	Cert Authorities:
2019-04-21T21:47:51.154-0700	INFO	http-worker-197	stdout	<CN=iadhadoop-c33.server.hulu.com, OU=hulu-bdi, O=hulu, ST=beijing, C=US>
2019-04-21T21:47:51.154-0700	INFO	http-worker-197	stdout	<EMAILADDRESS=root-ca@hulu.com, CN=Certificate Authorization from Security of Hulu, OU=Security, O=Hulu INC, L=Santa Monica, ST=California, C=US>
2019-04-21T21:47:51.154-0700	INFO	http-worker-197	stdout	<CN=cc01.server.hulu.com, OU=hulu-bdi, O=hulu, L=beijing, ST=beijing, C=US>
2019-04-21T21:47:51.154-0700	INFO	http-worker-197	stdout	*** ServerHelloDone
2019-04-21T21:47:51.154-0700	INFO	http-worker-197	stdout	http-worker-197, WRITE: TLSv1.2 Handshake, length = 1485
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	http-worker-251, READ: TLSv1.2 Alert, length = 2
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	http-worker-251
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	, RECV TLSv1.2 ALERT:
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	fatal,
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	unknown_ca
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	http-worker-251, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: unknown_ca
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	http-worker-251, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: unknown_ca
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	http-worker-251, called closeOutbound()
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	http-worker-251, closeOutboundInternal()
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	http-worker-251
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	, SEND TLSv1.2 ALERT:
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	warning,
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	description = close_notify
2019-04-21T21:47:51.156-0700	INFO	http-worker-251	stdout	http-worker-251, WRITE: TLSv1.2 Alert, length = 2
```

My client code:
```
  KRB5_CONFIG = "/etc/krb5.conf"
    CA_BUNDLE = "/Users/chang.wu/work/workspace/hulu-github-src/hadoop-security/ca-bundle.pem"
    _auth = KerberosAuthentication(
        config=KRB5_CONFIG,
        service_name='presto',
        principal='chang.wu@STAGING.SERVER.ABC.COM',
        mutual_authentication=False,
        ca_bundle=CA_BUNDLE,
    )
    conn=prestodb.dbapi.connect(
        host='aa.server.hulu.com',
        port=7778,
        catalog='hive',
        schema='information_schema',
        http_scheme='https',
        auth=_auth,
        max_attempts=1,
    )
    cur = conn.cursor()
    cur.execute('SHOW tables')
    rows = cur.fetchall()
```

**Comment by electrum** [comment] 2019-04-22 23:18
I don't think this is related to Kerberos. This is failing during TLS connection establishment, which is before Kerberos. I'm confused by the errors and am not sure if this is a client problem or server problem. It is either

* the client does not trust the server certificate
* the server does not trust the client certificate

My suggestion is to make sure the certificates are working by using either the CLI or with the `curl` command.

**Comment by VicoWu** [comment] 2019-04-23 00:05
@electrum , yes, you are correct, it is an SSL error, which has nothing to do with kerberos. 
The client didn't provide a certification, the SSL for presto should be a one-way verification, am I right?  The certification I provided is just CA-Bundle cert, that is to say , a file with the CA certificate and the intermediate-ca certificate; 
the SSL for presto is a server-verification in client side, that is to say , we will have to provide the client CA Certificate to verify the presto server certificate during negotiation but the client didn't have to provide a certification to server during negotiation and the server didn't have to have a CA Certification in his keystore; So , for the unknown ca error, I doubt that it is just the client error because the server side didn't care about ca, right ?

**Comment by VicoWu** [comment] 2019-04-23 00:08
@electrum  in the presto cli example provided by presto official doc, it seems that the client didn't have to provide his certification, but just add the Coordinator's certification into client keystore as a trust cert, thus the client could trust the certification provided by Coordinator; But I didn't see any client certificate verification on the server side.

**Comment by electrum** [comment] 2019-04-23 02:00
Presto does support client certificates as an authentication method. The validation on the server happens inside Jetty (or the JDK SSL code) during TLS connection establishment. (Presto has `CertificateAuthenticator` which will be used if `http-server.authentication.type` includes `CERTIFICATE`. This authenticator merely validates that a client certificate was provided.)

Based on your explanation and code, it sounds like there is no client certificate, so we can assume this is the client failing to validate the server certificate. Though I'm not sure why the server sees a `unknown_ca` error, unless the client sends that to the server?

Note that the Presto CLI does support client certificates using the `--keystore-path` option.

Can you try running the Presto CLI using the `--truststore-path` with the CA bundle file? The CLI supports PEM files so it should work (doesn't need to be a Java keystore).

**Comment by VicoWu** [comment] 2019-04-23 10:33
@electrum 
```
chang.wu@kerberos-test-vm2:~$ ${FIREWORK_HOME}/bin/presto   --server https://iadhadoop-b34.server.hulu.com:7778  --krb5-config-path /etc/krb5.conf  --krb5-principal bdi.prod@STAGING.SERVER.HULU.COM  --krb5-keytab-path /home/CORP/bdi.prod/bdi.prod.keytab --truststore-path /home/CORP/chang.wu/ca/intermediate/certs/ca-chain.cert.pem --krb5-remote-service-name presto  --catalog hive
presto:default> show catalogs;
Error running command: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
And in the server side ,it shows:

```
2019-04-23T03:20:57.504-0700	INFO	http-worker-191	stdout	*** ServerHelloDone
2019-04-23T03:20:57.504-0700	INFO	http-worker-191	stdout	http-worker-191, WRITE: TLSv1.2 Handshake, length = 1365
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	http-worker-785, READ: TLSv1.2 Alert, length = 2
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	http-worker-785
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	, RECV TLSv1.2 ALERT:
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	fatal,
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	certificate_unknown
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	http-worker-785, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	http-worker-785, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: certificate_unknown
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	http-worker-785, called closeOutbound()
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	http-worker-785, closeOutboundInternal()
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	http-worker-785
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	, SEND TLSv1.2 ALERT:
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	warning,
2019-04-23T03:20:57.505-0700	INFO	http-worker-785	stdout	description = close_notify
```

**Comment by VicoWu** [comment] 2019-04-23 11:29
@electrum 
When deploying Presto Coordinator on HTTPS, I followed this link(https://prestosql.io/docs/current/security/tls.html#server-java-keystore)
But there are something very blurry:
Firstly, we create the keystore file for coordinator:
```
keytool -genkeypair -alias presto -keyalg RSA -keystore keystore.jks
Enter keystore password:
Re-enter new password:
What is your first and last name?
  [Unknown]:  presto-coordinator.example.com
What is the name of your organizational unit?
  [Unknown]:
What is the name of your organization?
  [Unknown]:
What is the name of your City or Locality?
  [Unknown]:
What is the name of your State or Province?
  [Unknown]:
What is the two-letter country code for this unit?
  [Unknown]:
Is CN=presto-coordinator.example.com, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown correct?
  [no]:  yes

Enter key password for <presto>
        (RETURN if same as keystore password):
```
Then, that's everything what coordinator needs? 

But then , the document also says in the **Java Truststore File for TLS** part,  we have to use command 
```$ keytool -import -v -trustcacerts -alias presto_trust -file presto_certificate.cer -keystore presto_trust.jks -keypass <truststore_pass>
```
to import `presto_certificate.cer ` to a truststore. 
From my understanding, the **truststore** is different from coordinator **keystore**, instead, it is just used in client side like CLI, right? 
Then, what is `presto_certificate.cer `? how can I create this certificate? Did this certificate just means that I should export the certificate from coordinator keystore and dump it to `presto_certificate.cer `, right?

**Comment by electrum** [comment] 2019-04-24 06:29
I understand your confusion now. That documentation is rather out of date and the two sections are actually describing two different things (not something you can follow as a tutorial).

You are correct that the KeyStore example is like a root CA because it is self-signed.

The TrustStore example is for creating a Java TrustStore from an existing CA certificate file (of the CA that signed the server's certificate). This is not needed anymore because Presto (server, CLI, JDBC) supports PEM files directly, so you can give it the original certificate file.

I think you can export the certificate from the KeyStore like this:
```
keytool -export -rfc -alias presto -file presto.crt -keystore keystore.jks
```

That file would then be usable as the certificate bundle for the Presto CLI or Python.

**Comment by VicoWu** [comment] 2019-04-25 05:33
Yes, you are correct. I just export the certificate from the coordinator keystore and use it as the CA BUNDLE and it works now. But just as I asked before, since we already created a self-signed CA for our whole hadoop cluster, is it possible to use this CA to signed a cert for Presto Coordinator, then the CA BUNDLE will be our hadoop cluster ca, instead of a presto-specific CA?

**Comment by electrum** [comment] 2019-04-25 07:44
That should work. There’s nothing special about TLS in Presto. It’s all standard by design.

**Comment by VicoWu** [comment] 2019-04-28 02:01
> I understand your confusion now. That documentation is rather out of date and the two sections are actually describing two different things (not something you can follow as a tutorial).
> 
> You are correct that the KeyStore example is like a root CA because it is self-signed.
> 
> The TrustStore example is for creating a Java TrustStore from an existing CA certificate file (of the CA that signed the server's certificate). This is not needed anymore because Presto (server, CLI, JDBC) supports PEM files directly, so you can give it the original certificate file.
> 
> I think you can export the certificate from the KeyStore like this:
> 
> ```
> keytool -export -rfc -alias presto -file presto.crt -keystore keystore.jks
> ```
> That file would then be usable as the certificate bundle for the Presto CLI or Python.

Yes, I do export the self-signed rootca-like certificate from the coordinator keystore and use it as the presto cli and Python; It succeeded.
But my question still exists, what if I want to use a normal certification dedicated for coordinator? How could import this certificate to coordinator keystore? I tried to replace the self-signed certificate with the certificate dedicated for Coordinator(Remove the self-signed cert whose alias is `presto` and re-import the manually signed certificate with alias `presto` ), but it doesn't work;

**Comment by electrum** [comment] 2019-04-28 05:11
The easiest way is to use a PEM file. Just concatenate the private key and certificate files that you’d use for non-Java programs.

This script we use for tests shows how to generate a CA, server, and client certificates (might give you some ideas): https://github.com/airlift/airlift/blob/master/http-server/src/test/resources/clientcert-pem/clientcert-pem.sh

**Comment by findepi** [comment] 2020-02-17 12:52
Based on the discussion I think we can close this as answered.
Of course we can continue discussing here or move to Slack.
If there is anything to be done in Python Client itself, please open
a new issue at https://github.com/prestosql/presto-python-client

BTW @VicoWu the current Python client coordinates on PyPI are
https://pypi.org/project/presto-client/ (the module name is just
`presto` now).

**Closed by findepi** 2020-02-17 12:52 UTC
