### ISSUE TITLE
hive connector distinct result when use except

### ISSUE THREAD

**Issue by cmwenxin** [prestosql/presto#2150] opened 2019-11-29 15:56 UTC
Recently，I use the hive connector to test except, the results are  de duplicated(distinct).The tbl1 and tbl2 are as follows:
tbl1:
![无标题](https://user-images.githubusercontent.com/23608704/69879633-e5885180-1302-11ea-86a6-5c7bbedc100a.png)
tbl2:
![无标题](https://user-images.githubusercontent.com/23608704/69879692-0b155b00-1303-11ea-94e3-6886cdf5a05c.png)
test sql are as follows:
`select * from (select id,name from tbl1 except select id,name from tbl2 where company ='abc')`
but i do not use 'distinct',the result are as follows:
![无标题](https://user-images.githubusercontent.com/23608704/69879965-bcb48c00-1303-11ea-9b3b-36c92b88c764.png)

**Comment by findepi** [comment] 2019-11-29 16:17
@cmwenxin this is working as it should, `EXCEPT` does not maintain duplicate rows.

You can use `NOT IN` if you need to maintain duplicates:
```sql
SELECT id, name FROM tbl1
WHERE (id, name) NOT IN (SELECT (id, name) FROM tbl2 WHERE company = 'abc')
```

**Comment by cmwenxin** [comment] 2019-11-29 16:22
I use hive client to execute the same SQL, and the result is not to remove the duplication

**Comment by electrum** [comment] 2019-11-29 16:54
Presto follows the SQL standard for set operations. It sounds like Hive does not. You can read about the expected behavior in the documentation for PostgreSQL (which also follows the SQL standard): https://www.postgresql.org/docs/current/queries-union.html

> `EXCEPT` returns all rows that are in the result of query1 but not in the result of query2. (This is sometimes called the difference between two queries.) Again, duplicates are eliminated unless `EXCEPT ALL` is used. 

`EXCEPT ALL` is not yet implemented in Presto, but you can write the query the way @findepi showed to get the same behavior.

The same behavior applies for `UNION` -- duplicates are removed unless `UNION ALL` is used.

Note that the full syntax for set operations like `EXCEPT` is as follows:

```
EXCEPT [ DISTINCT | ALL ]
```

`EXCEPT` by itself is short for `EXCEPT DISTINCT`. So you can write `EXCEPT DISTINCT` in your query to be explicit about the desired behavior.

**Comment by martint** [comment] 2019-11-29 16:55
`X EXCEPT Y` is equivalent to `X EXCEPT DISTINCT Y`, so the `DISTINCT` in the set operation is implicit. In that scenario, only one copy of each duplicate row in `X` is retained.

From the SQL specification:

```
1) Let R be a row that is a duplicate of some row in ET1 or of some row in ET2 or both. Let m be the number of duplicates 
    of R in ET1 and let n be the number of duplicates of R in ET2, where m ≥ 0 and n ≥ 0.
2) If DISTINCT is specified or implicit, then 
Case:
     ...
    B) If EXCEPT is specified, then
    Case:
        I) If m > 0 and n = 0, then T contains exactly one duplicate of R.
        II) Otherwise, T contains no duplicate of R.
```

What you want is `X EXCEPT ALL Y`, but unfortunately that's not yet implemented in Presto.

**Comment by electrum** [comment] 2019-11-29 16:55
I'm going to close this issue since Presto has the expected behavior (per the SQL standard).

Please join us on Slack if you'd like to discuss this further: https://prestosql.io/slack.html

**Closed by electrum** 2019-11-29 16:55 UTC

**Comment by martint** [comment] 2019-11-29 16:59
I filed an issue for adding support for `ALL` with `EXCEPT` and `INTERSECT`: https://github.com/prestosql/presto/issues/2152
