### ISSUE TITLE
Presto 303 not respect uppercase username in hive metastore

### ISSUE THREAD

**Issue by MichaelZhao9824** [prestosql/presto#280] opened 2019-02-21 12:50 UTC
Presto 303 not respect uppercase username in hive metastore (Hive 2.3.4) which lost permissions to access tables (SQLstandard)

but it is working with 0.214.

**Comment by electrum** [comment] 2019-02-21 19:13
This might be related to the change add SQL role support. I can’t think of any other changes in this area.

**Comment by MichaelZhao9824** [comment] 2019-02-22 01:10
Could be. I believe you guys have done a few refactoring on that part. Could you please have a look? Thanks.
We use quite a few uppercase usernames and block us to upgrade to latest version.

it seems that it cannot get role info based on uppercase username because we set up permissions based on role

**Comment by kokosing** [comment] 2019-02-22 11:17
Let me try to reproduce it and cover with that case with a test.

**Comment by sopel39** [comment] 2019-02-22 11:52
@MichaelZhao9824 
1. What is the output of `SHOW ROLE GRANTS/SHOW ROLES/SHOW CURRENT ROLES`
2. Is this and admin user in question?

**Comment by kokosing** [comment] 2019-02-22 11:58
@MichaelZhao9824 Please see https://github.com/prestosql/presto/pull/289, and could you please tell me what I am missing there because test is passing.

**Comment by MichaelZhao9824** [comment] 2019-02-22 12:18
it is not a admin user. 

hive> SHOW ROLE GRANT user SVC_XXX;
OK
public	false	0
xxx_role	true	1549247879000	root
Time taken: 0.019 seconds, Fetched: 2 row(s)

The role is shared by over 50 users. Any user with lowercase user name gets permissions granted to the role. But the uppercase one does not get any permissions.

I set up roles and permissions from Hive not by Presto.

**Comment by kokosing** [comment] 2019-02-22 12:42
@MichaelZhao9824 Would you mind to test if https://github.com/prestosql/presto/pull/289 fixes your issue?

**Comment by kokosing** [comment] 2019-02-22 12:43
> Please see #289, and could you please tell me what I am missing there because test is passing.

I noticed that user (role) name that was passed to Hive was lower cased in Presto. Because of that test was passing.

**Comment by MichaelZhao9824** [comment] 2019-02-24 23:28
Thanks. will it be included in version 304?

**Comment by kokosing** [comment] 2019-02-25 09:43
I think so.

**Comment by MichaelZhao9824** [comment] 2019-02-25 22:52
@kokosing  thanks a lot, that would be very helpful. One more question, when do you guys plan to release 304?

**Comment by kokosing** [comment] 2019-02-26 08:52
Soon. I think it waits only for #289

**Comment by kokosing** [comment] 2019-02-26 12:51
Fixed via #289

**Closed by kokosing** 2019-02-26 12:51 UTC
