### ISSUE TITLE
Reading timestamp with type INT64 in parquet file

### ISSUE THREAD

**Issue by prakharjain-vogo** [prestosql/presto#2220] opened 2019-12-06 13:12 UTC
I am using AWS EMR 5.28.0 which has Presto 0.227 (Somehow, it works in AWS Athena.)
I have an AWS DMS job that migrates the AWS RDS data to S3. While migrating it also converts to Parquet. When setting target endpoint in S3, I have tried all combinations of parameters
`parquetTimestampInMillisecond` and `parquetVersion`, but none works.

Ideally, when I set AWS `parquetTimestampInMillisecond` to true, I should be able to read any timestamp column from Presto.
But, I get the following error:
`The column columnName is declared as type timestamp, but the Parquet file declares the column as type INT64`

Using parquet-tools, I see following output for the timestamp column in my parquet file in S3:
`columnName:  INT64 UNCOMPRESSED DO:0 FPO:99321 SZ:24381/24381/1.00 VC:3041 ENC:PLAIN,RLE ST:[min: 2019-11-26T04:21:44.403, max: 2019-11-26T04:22:45.932, num_nulls: 0]`
When I use following definition to create table, it works
```sql
CREATE TABLE hive.bigdata.tableName (
   columnName bigint
)
WITH (                                                                                          
    external_location = 's3://location', 
    format = 'PARQUET'                                                                           
 )
```

But I have to create a view to read column as timestamp,
```sql
CREATE VIEW hive.bigdata.tableName2 AS SELECT
cast(date_format(from_unixtime(columnName/1000), '%Y-%m-%d %h:%i:%s') as timestamp) as columnName
FROM hive.bigdata.tableName
```

Is there any direct way to create a table from the INT64 column?
or any way to tell AWS DMS to transfer in supported data type.

**Comment by prakharjain-vogo** [comment] 2019-12-10 10:07
anyone know why it is working in Athena?
In Athena If I declare table as `CREATE EXTERNAL TABLE tableName3 (
columnName timestamp
)ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://location'
TBLPROPERTIES (
  'has_encrypted_data'='false', 
  'transient_lastDdlTime'='1574669436')

it works

**Comment by prakharjain-vogo** [comment] 2019-12-10 12:39
Does hive implements read from INT64 Parquet timestamp files?
I found this issue, but no solution yet.
https://issues.apache.org/jira/browse/HIVE-13435

**Comment by prakharjain-vogo** [comment] 2019-12-10 12:46
There are two ways of converting bigint to timestamp as I did in view:

1. `cast(date_format(from_unixtime(columnName/1000), '%Y-%m-%d %h:%i:%s') as timestamp)`
2. `from_unixtime(cast(substr(cast(columnName as varchar),1,10) as int))`

**Comment by findepi** [comment] 2019-12-10 14:37
@prakharjain-vogo can you create an example file exposing the problem (with no confidential data) and attach it here?
(you may need to create .zip for github)

**Comment by prakharjain-vogo** [comment] 2019-12-10 15:28
I can give you the values of this bigint field, e.g. `1572184891087`, `1572184795148`, `1572186288573` which corresponds to time. You can then convert them to standard time by any online website such as https://www.unixtimestamp.com/index.php REMEMBER, you have to take the first 10 digits, and last 3 digits are decimal points millis. So for e.g. `1572184891087` -> `2019-10-27T14:01:31.087`

**Comment by ryanrupp** [comment] 2019-12-10 16:27
This is from a schema validation change that only exists in PrestoDB for Parquet, see this line here - https://github.com/prestodb/presto/commit/5d18a1c01d048bec435e587887bf20ffbe9794f8#diff-fba2eb40e1dce377dfe805d8d45f4af0R373 

Suggest logging this case in the PrestoDB repo

**Comment by findepi** [comment] 2019-12-10 16:56
@ryanrupp I believe the issue is about compatibility between Presto and AWS DMS in general. 
It's not limited to Facebook Presto, so it's good that @prakharjain-vogo reported this to us.

@prakharjain-vogo would you be able to attach a sample file? It could help fix the issue when someone picks this up.

**Comment by ryanrupp** [comment] 2019-12-10 17:07
@findepi there may be something more going on here but the error message mentioned is from a Facebook Presto specific check (linked above) that is relatively new so doesn't exist in PrestoSQL. There are some other pending pull requests like allowing statistics pruning for timestamps that are int64 so I guess I'd be surprised if it's broken. It is possible it's something like AWS DMS creates the type as int64 but doesn't tag it as a logical type of TIMESTAMP_MILLIS or something along those lines but the Parquet tools metadata there shows it rendering correctly the min/max stats for int64 in timestamp format (I think that means logical type is applied correctly).

@prakharjain-vogo would it be possible to test locally with the latest PrestoSQL (I know this is not on EMR unfortunately)

**Comment by findepi** [comment] 2019-12-10 19:08
@ryanrupp i understand what you're saying now.

>  would it be possible to test locally with the latest PrestoSQL

@ryanrupp very good idea!

@prakharjain-vogo 
you can run 1-node PrestoSQL on AWS very easily using `prestosql/presto` docker image.
alternatively, you can use Starburst Presto for AWS "one-click" installation (https://aws.amazon.com/marketplace/pp/B07DKV5659).
This isn't updated yet to the latest Presto SQL, but if the code Parquet works OK with latest Starburst Presto, it should work OK with latest Presto SQL as well.

**Comment by ryanrupp** [comment] 2020-01-03 03:20
Going to close as this was an issue in PrestoDB that got fixed in the previously mentioned linked issue. @prakharjain-vogo feel free to reopen if this is still an issue with PrestoSQL.

**Closed by ryanrupp** 2020-01-03 03:20 UTC
Labels: bug
