### ISSUE TITLE
support dynamically load the catalog properties? 

### ISSUE THREAD

**Issue by happyapple668** [prestosql/presto#5967] opened 2020-11-15 12:08 UTC
when the server started ,I add an new connector in directory etc/catalog, how can I use the new connector name in the query without restart the server

**Comment by tooptoop4** [comment] 2020-11-15 14:54
https://openlookeng.io/docs/docs/admin/dynamic-catalog.html
https://github.com/openlookeng/hetu-core

**Comment by findepi** [comment] 2020-11-15 22:43
This is currently not supported.
I'm closing the issue, as technically speaking, it's a duplicate of https://github.com/prestosql/presto/issues/2110

I invite you to share your use case  on [our slack](https://prestosql.io/slack.html), maybe someone can help find some other solution.
See you there!

**Closed by findepi** 2020-11-15 22:43 UTC
