### ISSUE TITLE
[PrestoSQL 316] Select filter query from prestocli fails with decimal overflow error 

### ISSUE THREAD

**Issue by chetandb** [prestosql/presto#4816] opened 2020-08-13 15:23 UTC
Environment - PrestoSQL 316, Spark 2.4.5, Carbon 2.0.1

Steps -
From SparkSQL create carbondata table and load data to table.
create table Test_Boundary (c1_int int,c2_Bigint Bigint,c3_Decimal Decimal(38,38),c4_double double,c5_string string,c6_Timestamp Timestamp,c7_Datatype_Desc string) stored as carbondata;
LOAD DATA INPATH 'hdfs://hacluster/chetan/Test_Data1.csv' INTO table Test_Boundary OPTIONS('DELIMITER'=',','QUOTECHAR'='','BAD_RECORDS_ACTION'='FORCE','FILEHEADER'='');

Issue : Select filter query from prestocli fails with decimal overflow error 
presto:chetan> select min(c3_Decimal),max(c3_Decimal),sum(c3_Decimal),avg(c3_Decimal) , count(c3_Decimal), variance(c3_Decimal) from test_boundary where exp(c1_int)=0.0 or exp(c1_int)=1.0;

Query 20200804_142831_00527_ed34h, FAILED, 2 nodes
Splits: 18 total, 17 done (94.44%)
0:00 [16 rows, 0B] [63 rows/s, 0B/s]

Query 20200804_142831_00527_ed34h failed: Decimal overflow

Log-
2020-08-04T22:28:31.712+0800 ERROR remote-task-callback-635 io.prestosql.execution.StageStateMachine Stage 20200804_142831_00527_ed34h.0 failed
java.lang.ArithmeticException: Decimal overflow
 at io.prestosql.spi.type.UnscaledDecimal128Arithmetic.throwOverflowException(UnscaledDecimal128Arithmetic.java:1663)
 at io.prestosql.spi.type.UnscaledDecimal128Arithmetic.throwIfOverflows(UnscaledDecimal128Arithmetic.java:807)
 at io.prestosql.operator.aggregation.DecimalSumAggregation.outputLongDecimal(DecimalSumAggregation.java:174)
 at io.prestosql.$gen.Decimal_38_38_Decimal_38_38_SumAccumulator_20200804_142831_454.evaluateFinal(Unknown Source)
 at io.prestosql.operator.Aggregator.evaluate(Aggregator.java:71)
 at io.prestosql.operator.AggregationOperator.getOutput(AggregationOperator.java:181)
 at io.prestosql.operator.Driver.processInternal(Driver.java:379)
 at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
 at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
 at io.prestosql.operator.Driver.processFor(Driver.java:276)
 at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
 at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
 at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
 at io.prestosql.$gen.Presto_316____20200804_043006_1.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

2020-08-04T22:28:31.721+0800 INFO dispatcher-query-471 io.prestosql.event.QueryMonitor TIMELINE: Query 20200804_142831_00527_ed34h :: Transaction:[964fbdbf-23e5-4e54-b54a-a10250944b25] :: elapsed 252ms :: planning 104ms :: waiting 22ms :: scheduling 41ms :: running 97ms :: finishing 10ms :: begin 2020-08-04T22:28:31.460+08:00 :: end 2020-08-04T22:28:31.712+08:00

**Comment by dain** [comment] 2020-08-13 18:04
If the sum overflows the type, the query fails.  This behavior is defined in the ANSI SQL spec we follow in Presto.

That said, it is possible this is caused by bad data in the Carbondata code you are using. How are you integrating with carbon data? I don't believe that Presto supports this natively.

I'm going to close this issue.  We can followup about the carbondata code in one of the other issues you filed.

**Closed by dain** 2020-08-13 18:04 UTC
