### ISSUE TITLE
presto query oracle number column

### ISSUE THREAD

**Issue by anuhewa** [prestosql/presto#2384] opened 2020-01-02 07:27 UTC
when i query oracle table from presto(presto db 0.228)   i am getting below issue for number columns

oracle side data type - number

sample value of column 1 = 10771.6719559045

i am trying to convert as decimal but failed

```
presto>
presto> select cast(column1 AS decimal(15,10)) from tablename1 where time_day_key between 2019110100 and 2019113023;

Query 20191227_105131_00050_fnuey, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0:08 [4.2M rows, 0B] [511K rows/s, 0B/s]

Query 20191227_105131_xxxxx_fnuey failed: Rounding necessary

presto>
```

==========trace=============

```
com.facebook.presto.spi.PrestoException: Rounding necessary
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:236)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.getSlice(JdbcRecordCursor.java:176)
        at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:126)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_228_bcf44e4____20191227_035504_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArithmeticException: Rounding necessary
        at java.math.BigDecimal.commonNeedIncrement(BigDecimal.java:4148)
        at java.math.BigDecimal.needIncrement(BigDecimal.java:4355)
        at java.math.BigDecimal.divideAndRound(BigDecimal.java:4330)
        at java.math.BigDecimal.setScale(BigDecimal.java:2470)
        at java.math.BigDecimal.setScale(BigDecimal.java:2386)
        at com.facebook.presto.spi.type.Decimals.encodeScaledValue(Decimals.java:161)
        at com.facebook.presto.plugin.jdbc.StandardReadMappings.lambda$decimalReadMapping$2(StandardReadMappings.java:105)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.getSlice(JdbcRecordCursor.java:173)
```
- show quoted text -

=========trace===============

kindly help

**Comment by ebyhr** [comment] 2020-01-02 07:39
@anuhewa I guess you are using a custom connector and it isn't a bug in this repository. 
Could you join `#troubleshooting` channel of the community Slack https://prestosql.io/slack.html?

**Comment by ebyhr** [comment] 2020-01-02 07:52
I'm closing this issue as it's not a bug. Let's talk on `#troubleshooting` channel as I already posted it.

**Closed by ebyhr** 2020-01-02 07:52 UTC

**Comment by findepi** [comment] 2020-01-02 07:53
i replied on the slack thread -- https://prestosql.slack.com/archives/CGB0QHWSW/p1577951410087200?thread_ts=1577951246.086800&cid=CGB0QHWSW

**Comment by Eliah7** [comment] 2022-12-07 07:40
@findepi The slack channel is not open for public access, may you please share the solution here.

**Comment by ebyhr** [comment] 2022-12-07 07:42
@Eliah7 Could you join from https://trino.io/slack.html?

**Comment by Eliah7** [comment] 2022-12-07 08:05
Thank you @ebyhr

**Comment by hashhar** [comment] 2022-12-07 09:12
For future reference the solution is documented at https://trino.io/docs/current/connector/oracle.html#number-to-decimal-configuration-properties
