### ISSUE TITLE
"http.server.authentication.krb5.principal-hostname" property doesn't work

### ISSUE THREAD

**Issue by yunitto** [prestosql/presto#1975] opened 2019-11-07 10:00 UTC
Environment: Presto 0.228 / Centos 7 / openjdk version "1.8.0_232"

Hi, I'm trying to run Presto on my server and follwed the official documentation to configure the coordinator with kerberos authentication. Setting `http.server.authentication.krb5.principal-hostname` property in config.properties file, as written in the [documentation](https://prestodb.github.io/docs/current/security/server.html), gives the error below when I'm trying to start server.

```
2019-11-07T18:29:48.464+0900    ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Configuration property 'http.server.authentication.krb5.principal-hostname' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'http.server.authentication.krb5.principal-hostname' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:128)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:74)
```

Server starts successfully when the property is not set. I looked at the server run log below,
```
2019-11-07T18:29:47.801+0900    INFO    main    Bootstrap       http.authentication.krb5.config
2019-11-07T18:29:47.802+0900    INFO    main    Bootstrap       http.server.authentication.krb5.keytab
2019-11-07T18:29:47.802+0900    INFO    main    Bootstrap       http.authentication.krb5.principal-hostname
2019-11-07T18:29:47.802+0900    INFO    main    Bootstrap       http.server.authentication.krb5.service-name
```
and found a very similar property -  `http.authentication.krb5.principal-hostname`. Is this the right one to set? Perhaps the documentation is wrong?

Thanks in advance.

**Comment by findepi** [comment] 2019-11-07 11:53
Hi @yunitto,

for this type of questions we recommend using `#troubleshooting` channel on our slack https://prestosql.io/slack.html
would you mind moving the conversation there?

**Comment by findepi** [comment] 2019-11-07 14:05
BTW Can you try again on Presto 324 (https://prestosql.io/download.html)?

(I'm closing this as not a bug; we can continue conversation here, but I recommend again using Slack instead.)

**Closed by findepi** 2019-11-07 14:05 UTC

**Comment by yunitto** [comment] 2019-11-07 15:13
@findepi Thanks for the notice! I'll move to slack.
