### ISSUE TITLE
Add support for Authenticator plugins

### ISSUE THREAD

**Issue by knwg145** [prestosql/presto#3572] opened 2020-04-28 16:04 UTC
We have an internal authenticator implementing the Authenticator interface. That authenticator will integrate with various internal libraries and currently uses various information from the HttpServletRequest. There is a PasswordAuthenticator but the interface only passes in a user and password, whereas we need other information from the HttpServletRequest. Specifically we are using:

-headers (AUTHORIZATION and X_FORWARDED_FOR)
-remote address

We want to move this internal authenticator out of the Presto code into its own plugin, so we want to see if we can create a mechanism to load Authenticators into Presto. What would be an appropriate interface for this?

**Comment by electrum** [comment] 2020-04-28 16:19
Do you need the ability to send back a `WWW-Authenticate` header on failure?

**Comment by knwg145** [comment] 2020-04-28 16:52
yes

**Comment by electrum** [comment] 2020-05-07 17:56
Duplicate of #2117

**Closed by electrum** 2020-05-07 17:56 UTC
