### ISSUE TITLE
Query spans only 2 partitions, but failed with more than 30 partitions limit

### ISSUE THREAD

**Issue by jiegzhan** [prestosql/presto#3113] opened 2020-03-16 19:54 UTC
Hello, my hive external table partitioned by date_key, one user sent me a query which says Query over table 'fact_voice_logs' can potentially read more than 30 partitions , but the query only spans 2 days .

```
SELECT DISTINCT(device_id)
from fact_voice_logs v 
WHERE cast(v.date_key as date) >= cast('2020-02-01' as date) and cast(v.date_key as date) <= cast('2020-02-02' as date) and v.log_id = 'sessionStart'
```
I dropped cast as date part and it worked.
```
SELECT DISTINCT(device_id)
from fact_voice_logs v 
WHERE v.date_key >= '2020-02-01' and v.date_key <= '2020-02-02' and v.log_id = 'sessionStart'
```
You guys saw this before? Thanks for your input.

**Comment by jiegzhan** [comment] 2020-03-16 19:56
![Screen Shot 2020-03-16 at 12 56 13 PM](https://user-images.githubusercontent.com/10664626/76795044-8cdfa600-6785-11ea-8679-988a351b32ab.png)

**Comment by electrum** [comment] 2020-03-16 19:59
Duplicate of #3112

**Closed by electrum** 2020-03-16 19:59 UTC
