### ISSUE TITLE
Incorrect Kudu predicate pushdowm

### ISSUE THREAD

**Issue by kokosing** [prestosql/presto#2963] opened 2020-02-28 11:56 UTC
```
1.create table kudu.test.test1
CREATE TABLE kudu.test.test2test1 (
   finishedtime timestamp WITH ( primary_key = true ),
   uid bigint WITH ( primary_key = true ),
   order_no varchar WITH ( primary_key = true ),
   id bigint WITH ( nullable = true ),
   total_fee decimal(10,2) WITH ( nullable = true ),
   verifytime timestamp WITH ( nullable = true ),
   reg_time timestamp WITH ( nullable = true )
)
WITH (
   number_of_replicas = 1,
   partition_by_hash_buckets = 3,
   partition_by_hash_columns = ARRAY['uid'],
   partition_by_range_columns = ARRAY['finishedtime'],
   range_partitions = '[{"lower":"2018-01-01T00:00:00.000Z","upper":"2021-01-01T00:00:00.000Z"}]'
)
​
2.create table kudu.test.test2
CREATE TABLE kudu.test.test2 (
   order_no varchar WITH ( primary_key = true ),
   verifytime timestamp WITH ( primary_key = true )
)
WITH (
   number_of_replicas = 1,
   partition_by_hash_buckets = 3,
   partition_by_hash_columns = ARRAY['order_no'],
   partition_by_range_columns = ARRAY['verifytime'],
   range_partitions = '[{"lower":"2018-01-01T00:00:00.000Z","upper":"2021-01-01T00:00:00.000Z"}]'
)
​
3.insert data into table  
insert into kudu.test.test1 values (timestamp '2020-02-25 08:00:01',1,'a1',1,125.2,timestamp '2020-02-25 08:20:00',timestamp '2020-02-20 08:00:00');
insert into kudu.test.test1 values (timestamp '2020-02-25 08:05:42',2,'a2',2,180.2,timestamp '2020-02-25 08:23:00',timestamp '2020-02-20 09:00:00');
insert into kudu.test.test1 values (timestamp '2020-02-25 08:12:33',3,'a3',3,550.2,timestamp '2020-02-25 08:32:00',timestamp '2020-02-20 10:00:00');
insert into kudu.test.test1 values (timestamp '2020-02-25 08:22:55',4,'b1',4,150.2,timestamp '2020-02-25 08:41:00',timestamp '2020-02-20 11:00:00');
insert into kudu.test.test1 values (timestamp '2020-02-25 08:31:12',5,'b2',5,120.2,timestamp '2020-02-25 08:49:00',timestamp '2020-02-20 12:00:00');
​
insert into kudu.test.test2 values ('a1',timestamp '2020-02-25 08:01:12');
insert into kudu.test.test2 values ('a2',timestamp '2020-02-25 08:21:22');
insert into kudu.test.test2 values ('b6',timestamp '2020-02-25 08:32:32');
insert into kudu.test.test2 values ('b7',timestamp '2020-02-25 08:33:12');
insert into kudu.test.test2 values ('c8',timestamp '2020-02-25 08:34:11');
​
4.use test sql in different version of presto
select uid,order_no,total_fee as total_fee1,total_fee as total_fee2,finishedtime as finishedtime1,finishedtime as finishedtime2,date_diff('day',reg_time,finishedtime)+1 as day_dif,reg_time
from kudu.test.test1 
where finishedtime > timestamp '2020-02-25 08:00:00' and finishedtime <= timestamp '2020-02-25 08:20:00'
and order_no not in 
(select order_no 
from kudu.test.test2
where verifytime > timestamp '2020-02-25 08:00:00' and verifytime <= timestamp '2020-02-25 08:20:00')  ; 
​
5.result  
   5.1 version of 322   -- only succeed
    uid | order_no | total_fee1 | total_fee2 |      finishedtime1      |      finishedtime2      | day_dif |        reg_time         
-----+----------+------------+------------+-------------------------+-------------------------+---------+-------------------------
   2 | a2       |     180.20 |     180.20 | 2020-02-25 08:05:42.000 | 2020-02-25 08:05:42.000 |       5 | 2020-02-20 09:00:00.000 
   3 | a3       |     550.20 |     550.20 | 2020-02-25 08:12:33.000 | 2020-02-25 08:12:33.000 |       5 | 2020-02-20 10:00:00.000
   
   5.2 version of 328   --failed
   Query 20200228_021532_00005_s4zi7 failed: Column (name: id, index: 3) is of type int64 but was requested as a type [Type: decimal]
   
   5.3 version of 330   --failed
   Query 20200228_021532_00005_s4zi7 failed: Column (name: id, index: 3) is of type int64 but was requested as a type [Type: decimal]
Collapse
```

Other test:
```
1.create table 
description
--The only differences between test1 and test3 are the type of total_fee. In test1 total_fee is decimal, In test3 total_fee is bigint(The same type with id and its index is just behind id)
CREATE TABLE kudu.test.test1 (
   finishedtime timestamp WITH ( primary_key = true ),
   uid bigint WITH ( primary_key = true ),
   order_no varchar WITH ( primary_key = true ),
   id bigint WITH ( nullable = true ),
   total_fee decimal(10,2) WITH ( nullable = true ),
   verifytime timestamp WITH ( nullable = true ),
   reg_time timestamp WITH ( nullable = true )
)
WITH (
   number_of_replicas = 1,
   partition_by_hash_buckets = 3,
   partition_by_hash_columns = ARRAY['uid'],
   partition_by_range_columns = ARRAY['finishedtime'],
   range_partitions = '[{"lower":"2018-01-01T00:00:00.000Z","upper":"2021-01-01T00:00:00.000Z"}]'
)
​
​
CREATE TABLE kudu.test.test2 (
   order_no varchar WITH ( primary_key = true ),
   verifytime timestamp WITH ( primary_key = true )
)
WITH (
   number_of_replicas = 1,
   partition_by_hash_buckets = 3,
   partition_by_hash_columns = ARRAY['order_no'],
   partition_by_range_columns = ARRAY['verifytime'],
   range_partitions = '[{"lower":"2018-01-01T00:00:00.000Z","upper":"2021-01-01T00:00:00.000Z"}]'
)
​
​
CREATE TABLE kudu.test.test3(
   finishedtime timestamp WITH ( primary_key = true ),
   uid bigint WITH ( primary_key = true ),
   order_no varchar WITH ( primary_key = true ),
   id bigint WITH ( nullable = true ),
   total_fee bigint WITH ( nullable = true ),
   verifytime timestamp WITH ( nullable = true ),
   reg_time timestamp WITH ( nullable = true )
)
WITH (
   number_of_replicas = 1,
   partition_by_hash_buckets = 3,
   partition_by_hash_columns = ARRAY['uid'],
   partition_by_range_columns = ARRAY['finishedtime'],
   range_partitions = '[{"lower":"2018-01-01T00:00:00.000Z","upper":"2021-01-01T00:00:00.000Z"}]'
)
​
​
2.insert test data 
description
--The only differences between test1 and test3 are the data of total_fee. 
insert into kudu.test.test1 values (timestamp '2020-02-25 08:00:01',1,'a1',1,125.2,timestamp '2020-02-25 08:20:00',timestamp '2020-02-20 08:00:00');
insert into kudu.test.test1 values (timestamp '2020-02-25 08:05:42',2,'a2',2,180.2,timestamp '2020-02-25 08:23:00',timestamp '2020-02-20 09:00:00');
insert into kudu.test.test1 values (timestamp '2020-02-25 08:12:33',3,'a3',3,550.2,timestamp '2020-02-25 08:32:00',timestamp '2020-02-20 10:00:00');
insert into kudu.test.test1 values (timestamp '2020-02-25 08:22:55',4,'b1',4,150.2,timestamp '2020-02-25 08:41:00',timestamp '2020-02-20 11:00:00');
insert into kudu.test.test1 values (timestamp '2020-02-25 08:31:12',5,'b2',5,120.2,timestamp '2020-02-25 08:49:00',timestamp '2020-02-20 12:00:00');
​
insert into kudu.test.test2 values ('a1',timestamp '2020-02-25 08:01:12');
insert into kudu.test.test2 values ('a2',timestamp '2020-02-25 08:21:22');
insert into kudu.test.test2 values ('b6',timestamp '2020-02-25 08:32:32');
insert into kudu.test.test2 values ('b7',timestamp '2020-02-25 08:33:12');
insert into kudu.test.test2 values ('c8',timestamp '2020-02-25 08:34:11');
​
insert into kudu.test.test3 values (timestamp '2020-02-25 08:00:01',1,'a1',1,125,timestamp '2020-02-25 08:20:00',timestamp '2020-02-20 08:00:00');
insert into kudu.test.test3 values (timestamp '2020-02-25 08:05:42',2,'a2',2,180,timestamp '2020-02-25 08:23:00',timestamp '2020-02-20 09:00:00');
insert into kudu.test.test3 values (timestamp '2020-02-25 08:12:33',3,'a3',3,550,timestamp '2020-02-25 08:32:00',timestamp '2020-02-20 10:00:00');
insert into kudu.test.test3 values (timestamp '2020-02-25 08:22:55',4,'b1',4,150,timestamp '2020-02-25 08:41:00',timestamp '2020-02-20 11:00:00');
insert into kudu.test.test3 values (timestamp '2020-02-25 08:31:12',5,'b2',5,120,timestamp '2020-02-25 08:49:00',timestamp '2020-02-20 12:00:00');
​
4.to do test
description
--The only difference between sql_1 and sql_2 is the table. 
​
sql_1    test1 and test2
select uid,order_no,total_fee as total_fee1,total_fee as total_fee2,finishedtime as finishedtime1,finishedtime as finishedtime2,date_diff('day',reg_time,finishedtime)+1 as day_dif,reg_time
from kudu.test.test1 
where finishedtime > timestamp '2020-02-25 08:00:00' and finishedtime <= timestamp '2020-02-25 08:20:00'
and order_no not in 
(select order_no 
from kudu.test.test2
where verifytime > timestamp '2020-02-25 08:00:00' and verifytime <= timestamp '2020-02-25 08:20:00')  ; 
​
sql_2  test3 and test2 
select uid,order_no,total_fee as total_fee1,total_fee as total_fee2,finishedtime as finishedtime1,finishedtime as finishedtime2,date_diff('day',reg_time,finishedtime)+1 as day_dif,reg_time
from kudu.test.test3 
where finishedtime > timestamp '2020-02-25 08:00:00' and finishedtime <= timestamp '2020-02-25 08:20:00'
and order_no not in 
(select order_no 
from kudu.test.test2
where verifytime > timestamp '2020-02-25 08:00:00' and verifytime <= timestamp '2020-02-25 08:20:00')  ; 
​
5.result  
 sql_1
   5.1.1 version of 322   -- only succeed and right
   
 uid | order_no | total_fee1 | total_fee2 |      finishedtime1      |      finishedtime2      | day_dif |        reg_time         
-----+----------+------------+------------+-------------------------+-------------------------+---------+-------------------------
   2 | a2       |     180.20 |     180.20 | 2020-02-25 08:05:42.000 | 2020-02-25 08:05:42.000 |       5 | 2020-02-20 09:00:00.000 
   3 | a3       |     550.20 |     550.20 | 2020-02-25 08:12:33.000 | 2020-02-25 08:12:33.000 |       5 | 2020-02-20 10:00:00.000
   
   5.1.2 version of 328   --failed
   Query 20200228_021532_00005_s4zi7 failed: Column (name: id, index: 3) is of type int64 but was requested as a type [Type: decimal]
   
   5.1.3 version of 330   --failed
   Query 20200228_021532_00005_s4zi7 failed: Column (name: id, index: 3) is of type int64 but was requested as a type [Type: decimal]
 
 
 sql_2
	All are succeed ---But, i think, The reason comes up
	
	5.2.1  result    version of 322     -- right result
 uid | order_no | total_fee1 | total_fee2 |      finishedtime1      |      finishedtime2      | day_dif |        reg_time         
-----+----------+------------+------------+-------------------------+-------------------------+---------+-------------------------
   2 | a2       |        180 |        180 | 2020-02-25 08:05:42.000 | 2020-02-25 08:05:42.000 |       5 | 2020-02-20 09:00:00.000 
   3 | a3       |        550 |        550 | 2020-02-25 08:12:33.000 | 2020-02-25 08:12:33.000 |       5 | 2020-02-20 10:00:00.000	
    
	5.2.2 result    version of 328 and 330     -- wrong results
 uid | order_no | total_fee1 | total_fee2 |      finishedtime1      |      finishedtime2      | day_dif |        reg_time         
-----+----------+------------+------------+-------------------------+-------------------------+---------+-------------------------
   2 | a2       |          2 |          2 | 2020-02-25 08:05:42.000 | 2020-02-25 08:05:42.000 |   18318 | 1970-01-01 08:00:00.000 
   3 | a3       |          3 |          3 | 2020-02-25 08:12:33.000 | 2020-02-25 08:12:33.000 |   18318 | 1970-01-01 08:00:00.000
```
--conclusion
You can see the column of total_fee1, day_dif and reg_time in sql_2's result
I think the reason is the index that you have been used by mistake in #2253

**Comment by JellyMing** [comment] 2020-03-04 16:58
Maybe I find something in the KuduRecordCursor class. 
`
   @Override
    public boolean advanceNextPosition()
    {
        boolean needNextRows = !started || !nextRows.hasNext();

        if (!started) {
            started = true;
        }

        if (needNextRows) {
            currentRow = null;
            try {
                do {
                    if (!scanner.hasMoreRows()) {
                        return false;
                    }

                    nextRows = scanner.nextRows();
                }
                while (!nextRows.hasNext());
                log.debug("Fetched " + nextRows.getNumRows() + " rows");
            }
            catch (KuduException e) {
                throw new RuntimeException(e);
            }
        }
        currentRow = nextRows.next();
        totalBytes += getRowLength();
        return `true;`
    }`

The problem is about index and currentRow. I have been found these codes and i don't know this line: currentRow = nextRows.next();   Why you can use this row to match the index ，I am confused

**Comment by wlichina111** [comment] 2020-03-09 08:13
Hi JellyMing, kokosing, Praveen2112,

I also reproduced this issue in 328. This issue seems not due to #2253, since the issue is not gone after revert the patch.

Compared to 323, I also notice one patch(#f9e1 Remove TableLayout API from Kudu Connector) remove tableLayout way in kudu connector and seems causing this issue. After revert it, the issue is gone.

Seems #f9e1 remove some deprecated function and replace tableLayout by connectorHandle, but may not handle or fill well some data like desiredColumns etc.

may investagating by checking this patch.

**Comment by wlichina111** [comment] 2020-03-09 08:16
seems the issue easily happens in subclause case like:

**Comment by wlichina111** [comment] 2020-03-09 08:18
seems the issue easily happens when has subQuery like: 
`select uid,order_no from kudu.t1.test1 where order_no not in ( select 'a2' a union select 'a3' a);`

**Comment by Praveen2112** [comment] 2020-03-19 03:20
@wlichina111 You were right. When we moved to the new TableLayout API for kudu connector, the project pushdown - `applyProject` didn't capture the exact desired set of columns to be scanned for queries involving `ApplyNode` and `CorrelatedJoinNode` so I guess it was failing for you. These are being resolved in #2843 and #2654. The latter was merged recently to the master branch so can you test it with the latest and let us know if it still fails.

**Comment by wlichina111** [comment] 2020-03-20 11:06
@Praveen2112 Thanks Praveen,seems the issue is gone with latest. @JellyMing FYI

**Comment by kokosing** [comment] 2020-03-20 12:42
Thank you @Praveen2112 on working on this.

**Closed** 2020-03-26 14:33 UTC
Labels: bug
