### ISSUE TITLE
Update Hive Statistics Failure

### ISSUE THREAD

**Issue by enaggar** [prestosql/presto#1994] opened 2019-11-09 02:43 UTC
Encountered the issue below on an INSERT query
```
io.prestosql.spi.PrestoException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.setPartitionColumnStatistics(ThriftHiveMetastore.java:517)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.setPartitionColumnStatistics(ThriftHiveMetastore.java:496)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.updatePartitionStatistics(ThriftHiveMetastore.java:477)
	at io.prestosql.plugin.hive.metastore.thrift.BridgingHiveMetastore.updatePartitionStatistics(BridgingHiveMetastore.java:119)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.updatePartitionStatistics(CachingHiveMetastore.java:358)
	at io.prestosql.plugin.hive.metastore.cache.CachingHiveMetastore.updatePartitionStatistics(CachingHiveMetastore.java:358)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore$UpdateStatisticsOperation.run(SemiTransactionalHiveMetastore.java:2572)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeUpdateStatisticsOperations(SemiTransactionalHiveMetastore.java:1452)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.access$1400(SemiTransactionalHiveMetastore.java:1043)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:990)
	at io.prestosql.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:891)
	at io.prestosql.plugin.hive.HiveMetadata.commit(HiveMetadata.java:2212)
	at io.prestosql.plugin.hive.HiveConnector.commit(HiveConnector.java:198)
	at io.prestosql.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:595)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
	at org.apache.hadoop.hive.metastore.api.StringColumnStatsData.validate(StringColumnStatsData.java:626)
	at org.apache.hadoop.hive.metastore.api.StringColumnStatsData$StringColumnStatsDataStandardScheme.write(StringColumnStatsData.java:718)
	at org.apache.hadoop.hive.metastore.api.StringColumnStatsData$StringColumnStatsDataStandardScheme.write(StringColumnStatsData.java:656)
	at org.apache.hadoop.hive.metastore.api.StringColumnStatsData.write(StringColumnStatsData.java:574)
	at org.apache.hadoop.hive.metastore.api.ColumnStatisticsData.standardSchemeWriteValue(ColumnStatisticsData.java:346)
	at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:244)
	at org.apache.thrift.TUnion$TUnionStandardScheme.write(TUnion.java:213)
	at org.apache.thrift.TUnion.write(TUnion.java:152)
	at org.apache.hadoop.hive.metastore.api.ColumnStatisticsObj$ColumnStatisticsObjStandardScheme.write(ColumnStatisticsObj.java:554)
	at org.apache.hadoop.hive.metastore.api.ColumnStatisticsObj$ColumnStatisticsObjStandardScheme.write(ColumnStatisticsObj.java:492)
	at org.apache.hadoop.hive.metastore.api.ColumnStatisticsObj.write(ColumnStatisticsObj.java:418)
	at org.apache.hadoop.hive.metastore.api.ColumnStatistics$ColumnStatisticsStandardScheme.write(ColumnStatistics.java:494)
	at org.apache.hadoop.hive.metastore.api.ColumnStatistics$ColumnStatisticsStandardScheme.write(ColumnStatistics.java:430)
	at org.apache.hadoop.hive.metastore.api.ColumnStatistics.write(ColumnStatistics.java:365)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$update_partition_column_statistics_args$update_partition_column_statistics_argsStandardScheme.write(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$update_partition_column_statistics_args$update_partition_column_statistics_argsStandardScheme.write(ThriftHiveMetastore.java)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$update_partition_column_statistics_args.write(ThriftHiveMetastore.java)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:71)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.send_update_partition_column_statistics(ThriftHiveMetastore.java:3868)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.update_partition_column_statistics(ThriftHiveMetastore.java:3860)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.setPartitionColumnStatistics(ThriftHiveMetastoreClient.java:205)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$setPartitionColumnStatistics$24(ThriftHiveMetastore.java:508)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
	at io.prestosql.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
	at io.prestosql.plugin.hive.metastore.thrift.ThriftHiveMetastore.setPartitionColumnStatistics(ThriftHiveMetastore.java:506)
	... 21 more
	Suppressed: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
		... 47 more
	Suppressed: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
		... 47 more
	Suppressed: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
		... 47 more
	Suppressed: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
		... 47 more
	Suppressed: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
		... 47 more
	Suppressed: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
		... 47 more
	Suppressed: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
		... 47 more
	Suppressed: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
		... 47 more
	Suppressed: org.apache.thrift.protocol.TProtocolException: Required field 'numDVs' is unset! Struct:StringColumnStatsData(maxColLen:11, avgColLen:0.0, numNulls:0, numDVs:0)
		... 47 more
```

**Comment by findepi** [comment] 2019-11-09 13:30
@enaggar  thanks for your report

*workaround*
you can avoid the failure by disabling stats collection on write (`set session hive.collect_column_statistics_on_write = false;` or `hive.collect-column-statistics-on-write` in hive.properties).

What's the Hive metastore version?
What's the table schema (`SHOW CREATE TABLE` in Hive)?
Can you reproduce this with a table that has just one `varchar` / `string` column?

**Comment by raunaqmorarka** [comment] 2019-11-11 07:32
@findepi 
I was also able to reproduce this with HMS 1.2
E.g.: 
CTAS succeeds:
`
create table example
as
SELECT * FROM
(VALUES
('2017-04-01 08:38:37.000')
) as T(st);
`
IOT fails:
`
insert overwrite example
SELECT * FROM
(VALUES
('2017-04-01 08:38:37.000')
) as T(st);
`
Output of show create table from Hive: 
`
CREATE TABLE example(
  st varchar(23))
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
  's3://xxx/example'
TBLPROPERTIES (
  'COLUMN_STATS_ACCURATE'='false', 
  'numFiles'='1', 
  'numRows'='-1', 
  'presto_query_id'='20191111_071943_00014_3jmwt', 
  'presto_version'='', 
  'rawDataSize'='-1', 
  'totalSize'='339', 
  'transient_lastDdlTime'='1573456787')
`

**Comment by findepi** [comment] 2019-11-11 10:06
@raunaqmorarka i followed your steps, but it didn't fail for me.
can you try reproducing this on `prestodev/hdp2.6-hive` environment? It has `Hive 1.2.1000.2.6.5.0-292` installed.

This this env is the default, you can bring it up with:
```
./mvnw clean install -DskipTests
./presto-product-tests/conf/docker/singlenode/compose.sh up
```

**Comment by Terry93** [comment] 2020-02-25 23:37
@enaggar @raunaqmorarka @findepi  We are also able to reproduce the issue using PrestoSQL 320 + HMS 1.2.1. I ran some tests and it seems that this issue will **only** occur to an insert statement after a CTAS on an unpartitioned table.

After the investigation, we found out the error happened on HMS, and the caller is Presto's `ThriftHiveMetastore.updateTableStatistics` the function where Presto will try to update stats after insert into a table.

Regarding the reason why 'numDVs' is unset, is because of `statistics.getDistinctValuesCount` at https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java#L864 return `Optional.empty` and thus causing `setNumDVs` not triggered.

The reason why `statistics.getDistinctValuesCount` returns `Optional.empty` is because https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java#L557 returns `Optional.empty`. Since the `rowCount` here is `Optional.empty`.

The reason why `rowCount` (aka `numRows` in HMS) is `Optional.empty` is because the table params `numRows` in HMS is -1 and Presto will treat it as empty. We found out that it is strange that the `numRows` is -1 after CATS. Thus we checked the HMS tag release-1.2.1 code, we saw that this is expected: https://github.com/apache/hive/blob/release-1.2.1/metastore/src/java/org/apache/hadoop/hive/metastore/MetaStoreUtils.java#L220 Since HMS will try to reset all require-compute-stats (a.k.a `numRows` and `rawDataSize`) to -1 for an unpartitioned table if `STATS_GENERATED_VIA_STATS_TASK` parameter is not carried in the alter table thrift call parameters. This param is introduced in https://issues.apache.org/jira/browse/HIVE-8648 per https://docs.cloudera.com/documentation/enterprise/5-2-x/topics/impala_perf_stats.html

To fix that, we can try to add this into the parameters we are constructing the `modifiedTable` object https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java#L485

**Comment by findepi** [comment] 2020-02-26 09:04
> We are also able to reproduce the issue using PrestoSQL 320 + HMS 1.2.1

Did you mean 330? Can you re-run your tests on 330?

**Comment by Terry93** [comment] 2020-02-26 15:53
@findepi I mean 320 (we use 320 as prod thus we investigated with this version first). Yes, I can test it against 330 sometime later.

**Comment by Terry93** [comment] 2020-03-03 06:11
@findepi actually it is fixed in https://github.com/prestosql/presto/commit/e9df8c8215f073d2512b22bf58e619de555d4396 so I don't have problem with it

**Comment by findepi** [comment] 2020-03-03 08:40
Thanks for checking.

**Closed by findepi** 2020-03-03 08:40 UTC
Labels: bug
