### ISSUE TITLE
Generic JDBC connector for any back-end data source that's currently not supported by presto

### ISSUE THREAD

**Issue by RugratsJ** [prestosql/presto#3204] opened 2020-03-23 00:01 UTC
Is it possible to create a generic JDBC connector for any back-end data source that's currently not supported by Presto? For example, for netezza, Oracle, etc, we could drop the Netezza/Oracle jar file to the generic-jdbc catalog folder after the installation.

**Comment by ebyhr** [comment] 2020-03-23 01:52
@RugratsJ Going to close this issue because it's a duplicate of https://github.com/prestosql/presto/issues/2910. You may want to try Starburst Presto https://docs.starburstdata.com/latest/connector/generic-jdbc.html if you are rush.

**Closed by ebyhr** 2020-03-23 01:52 UTC

**Comment by RugratsJ** [comment] 2020-03-23 06:23
Thank you very much ebyhr for your quick response. I have integrated the presto-oracle into my 331 version from PR #1959. So far so good. Amazing community. From my reading, the parallel read for JDBC connector could only be done at the individual connector level. Do we have to put in request to get the parallel read done for each connector, for example, postgresql, Oracle, etc.

**Comment by ebyhr** [comment] 2020-03-23 06:41
> Do we have to put in request to get the parallel read done for each connector, for example, postgresql, Oracle, etc.

You don't need to request for each JDBC connector. Please follow the https://github.com/prestosql/presto/issues/389 you already commented.

**Comment by tooptoop4** [comment] 2020-03-23 10:38
@RugratsJ try https://github.com/prestosql/presto/pull/3105
