### ISSUE TITLE
[PrestoSQL 316] Select filter query with ceil function fails in prestocli

### ISSUE THREAD

**Issue by chetandb** [prestosql/presto#4814] opened 2020-08-13 15:15 UTC
Environment - PrestoSQL 316, Spark 2.4.5, Carbondata 2.0.1

Steps-
From Spark-SQL create carbondata table and load data.
create table Test_Boundary (c1_int int,c2_Bigint Bigint,c3_Decimal Decimal(38,38),c4_double double,c5_string string,c6_Timestamp Timestamp,c7_Datatype_Desc string) stored as carbondata;
LOAD DATA INPATH 'hdfs://hacluster/chetan/Test_Data1.csv' INTO table Test_Boundary OPTIONS('DELIMITER'=',','QUOTECHAR'='','BAD_RECORDS_ACTION'='FORCE','FILEHEADER'='');

Issue -
Select filter query with ceil function fails in prestocli
presto:chetan> select c3_Decimal from test_boundary where ceil(c3_Decimal)=0.0 or ceiling(c3_Decimal) IS NULL;

Query 20200804_141632_00510_ed34h, FAILED, 2 nodes
Splits: 17 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200804_141632_00510_ed34h failed: 38

Log-
2020-08-04T22:16:32.628+0800 ERROR remote-task-callback-609 io.prestosql.execution.StageStateMachine Stage 20200804_141632_00510_ed34h.1 failed
java.lang.ArrayIndexOutOfBoundsException: 38
 at io.prestosql.operator.scalar.MathFunctions$Ceiling.ceilingLong(MathFunctions.java:286)
 at io.prestosql.operator.scalar.MathFunctions$Ceiling.ceilingLongShort(MathFunctions.java:296)
 at io.prestosql.$gen.PageFilter_20200804_141632_952.filter(Unknown Source)
 at io.prestosql.$gen.PageFilter_20200804_141632_952.filter(Unknown Source)
 at io.prestosql.operator.project.DictionaryAwarePageFilter.filter(DictionaryAwarePageFilter.java:83)
 at io.prestosql.operator.project.PageProcessor.createWorkProcessor(PageProcessor.java:115)
 at io.prestosql.operator.ScanFilterAndProjectOperator$SplitToPages.lambda$processPageSource$1(ScanFilterAndProjectOperator.java:254)
 at io.prestosql.operator.WorkProcessorUtils.lambda$flatMap$4(WorkProcessorUtils.java:246)
 at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
 at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
 at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
 at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
 at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
 at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
 at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
 at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
 at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
 at io.prestosql.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:278)
 at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:320)
 at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
 at io.prestosql.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:307)
 at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
 at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
 at io.prestosql.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:200)
 at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
 at io.prestosql.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:221)
 at io.prestosql.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:215)
 at io.prestosql.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:373)
 at io.prestosql.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:133)
 at io.prestosql.operator.Driver.processInternal(Driver.java:379)
 at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
 at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
 at io.prestosql.operator.Driver.processFor(Driver.java:276)
 at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
 at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
 at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
 at io.prestosql.$gen.Presto_316____20200804_042858_1.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)

2020-08-04T22:16:32.639+0800 INFO dispatcher-query-444 io.prestosql.event.QueryMonitor TIMELINE: Query 20200804_141632_00510_ed34h :: Transaction:[a2f9af2c-c2a4-474c-af8f-fd26a50f4335] :: elapsed 163ms :: planning 86ms :: waiting 18ms :: scheduling 37ms :: running 32ms :: finishing 8ms :: begin 2020-08-04T22:16:32.465+08:00 :: end 2020-08-04T22:16:32.628+08:00

**Comment by dain** [comment] 2020-08-13 18:12
I believe this is a duplicate of #4820

**Closed by dain** 2020-08-13 18:12 UTC
